<?php
// +----------------------------------------------------------------------
// | Created by PhpStorm
// +----------------------------------------------------------------------
// | Date: 18-4-8
// +----------------------------------------------------------------------
// | blog ( https://www.woann.cn )
// +----------------------------------------------------------------------
// | Author: Mr.wu <304550409@qq.com>
// +----------------------------------------------------------------------
namespace App\Utility;
use EasySwoole\Config;
use EasySwoole\Core\Swoole\Coroutine\AbstractInterface\CoroutinePool;
use EasySwoole\Core\Swoole\Coroutine\Client\Mysql;
class MysqlPool2 extends CoroutinePool
{
    function __construct($min, $max)
    {
        parent::__construct($min, $max);
    }
    function getObj($timeOut = 0.1):?Mysql
    {
        return parent::getObj($timeOut); // TODO: Change the autogenerated stub
    }
    protected function createObject()
    {
        // TODO: Implement createObject() method.
        $conf = Config::getInstance()->getConf('MYSQL');
        $db = new Mysql([
            'host' => $conf['HOST'],
            'username' => $conf['USER'],
            'password' => $conf['PASSWORD'],
            'db' => $conf['DB_NAME']
        ]);
        return $db;
    }
}